### ISSUE TITLE
Emulation too fast. Audio issues

### ISSUE THREAD

**Issue by lukasynthetic** [badda71/uae3DS#1]
New 2DS XL
Updated version 0.3 
Games: Lotus 2, Cannon Fodder

Lotus: Emulator runs too fast (ironically). Music is distorted and skipping, going out of sync. Some screen tearing. Crashes after couple of minutes. Tried few different versions.

Cannon Fodder: as above. Also background graphics skipping.

Compared to previous 0.3 - it was noticeably slow but music in Lotus was synced without skipping.

Thank you very much for your work. It's exciting to have Amiga on very suitable 2DS.

**Comment by badda71** [comment]
Fixed in v0.3.1
