### ISSUE TITLE
Potential typo preventing a successful build in the Uae3dsSDL src

### ISSUE THREAD

**Issue by secondchaos** [badda71/uae3DS#5]
In the file SDL_n3dsvideo.h which is located at /UAE3DS_SDL/src/video/n3ds the enum GSPGPU_FramebufferFormat from the 3ds devkitpro base files. It's used twice but it's written like GSPGPU_FramebufferFormats with the plural s. This resulted in build errors. The enum is defined in libctru/include/3ds/service/gspgpu.h 
This might be due to recent changes in this file.

**Comment by badda71** [comment]
fixed with https://github.com/badda71/uae3DS/commit/5f60be2982f44f5eb086cac42b21ad5e35342f14
